config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

root 'articles#index'
  get 'articles/home', to: 'articles#home'

resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

    validates :title, presence: true, length: {minimum: 5, maximum: 50}
    validates :description, presence: true, length: {minimum: 5, maximum: 100}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    
    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end


    def home

    end


    def create
        @article = Article.new(article_params)
        if @article.save
            flash[:success] = "Article created successfully"
            redirect_to article_path(@article)
        else
         render :new
        end
    end 

    def show
        @article = Article.find(params[:id])
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
        flash[:success]= "Article updated successfully"
        redirect_to edit_article_path
        end
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        flash[:danger]= "Article was successfully deleted"
        redirect_to articles_path
    end
end
    private 
    def article_params
        params.require(:article).permit(:title, :description)
    end    
    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<div class="container">
<%= render 'shared/errors', obj: @article %>

<div class="col-xs-5">
  <%= form_for(@article, :html => {class: "form-horizontal shadow p-3 mb-5 bg-brown rounded", role: "form"}) do |d| %>
    <div class="form-group">
      <div class="control-label offset-1 col-sm-8">
        <%= d.label :title %>
      </div>
      <div class="offset-1 col-sm-10">
        <%= d.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: "true" %>
      </div>
    </div> 
    
    <div class="form-group">
      <div class="control-label offset-1 col-sm-10">
        <%= d.label :description %>
      </div>
      <div class="offset-1 col-sm-10">
        <%= d.text_area :description, rows: 6, class: "form-control", placeholder: "Description of article", autofocus: "true" %>
      </div>
    </div>  
    <div class="offset-1 col-sm-6">
      <%= d.submit id: "submit" %>
    </div> 
  <p > 
  <% end %>    
     <div class="mb-6">
              <%= link_to "[ Cancel request and return to article listing", articles_path, id: "back" %> ]
      </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit existing article</h1>

<%= render "form" %>

</div>

app/views/articles/home.html.erb
<div id= "homepage">
<h1 style="padding:15px;font-size:42pt;font-weight:bolder;">ALPHA BLOG</h1>
<p>
<%= link_to "Sign Up", "#", id: "signup" %>
</div>

app/views/articles/index.html.erb
<h1 class="text-center mt-4"> Listing all articles</h1>
<% @articles.each do |article| %>
<div class="card text-center">
  <div class="card-header font-italic">
    by Thabang Mzamane
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= link_to article.title, article_path(article), class: " text-success" %></h5>
    <p class="card-text"><%= truncate(article.description, length:100) %></p>
    <%= link_to 'Show', article_path(article), class:"btn btn-outline-primary" %></td>
    <%= link_to 'edit', edit_article_path(article),  class:"btn btn-outline-info" %>
    <%= link_to 'delete', article_path(article), method: :delete,
                              data: {confirm: "Are you sure you want to delete the article?"},
                              class:"btn btn-outline-danger", text:"delete" %>
  </div>
  <div class="card-footer text-muted">
    edited ago </small>
  </div>
</div>
<% end %>
<p />
<%= link_to "Create new article",new_article_path, id: "create" %>
<p />

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create an article</h1>

<%= render "form" %>

app/views/articles/show.html.erb
<div id="container">
<h2 align="center">Title : <%= @article.title %></h2>
<div class="well">
    <h4 align="center"><strong>Description</strong></h4>
    <%= simple_format(@article.description) %>
    <div class="article-actions">
<%= link_to "Edit this article", edit_article_path, class: "btn btn-xs btn-primary" %> 
<%= link_to "Delete this article", article_path(@article), method: :delete,
                                   data: {confirm: "Are you sure you want to delete the article?"},
                                   class: "btn btn-xs btn-danger" %>
<%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
</div>
</div>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
    <div class="col-xs-10 col-xs-offset-2">
<% flash.each do |name,msg| %>
    <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss"alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
 ```</div>
<% end %> 
 </div>
</div>

app/views/layouts/_navigation.html.erb
      
<nav class="navbar navbar-expand-lg" id= "navbar">
  <%= link_to "ALPHA BLOG", articles_home_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">

      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
          <%= link_to "View article", articles_path, class: "dropdown-item" %>

          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alphablog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %> 
  
    <link href="https://fonts.googleapis.com/css?family=Jura&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>
<body>
<%= render 'layouts/navigation' %>
<%= render 'layouts/messages' %>

<div class="container">
<%= yield %>
</div>
<div id="sticky-footer" class="py-3 text-white">
  Copyright &copy; The Complete Ruby on Rails Developer<span style="color:black"> by Mashrur Hossain</div>
</div>
</body>

</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading"> 
          <h2 class="panel-title">
          <%= pluralize(obj.errors.count, "error") %>
          prohibited this article from being saved:
          </h2>
          <div class="panel-body">
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
          </ul>
          </div>
        </div>
      </div>
    </div>
 </div>   
<% end %>